// Code generated by go-bindata.
// sources:
// sample.cfg
// database.cfg
// DO NOT EDIT!

package configo

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _sampleCfg = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x8a\x76\x71\x75\x73\x0c\xf5\x09\x89\xe5\xca\xc8\x2f\x2e\xb1\x52\x48\xcf\x2c\xc9\x28\x4d\xd2\xcb\xc9\x4f\x4e\xcc\xe1\x2a\xc8\x2f\x02\x0a\x59\x18\x70\x15\x64\x5a\x29\x18\x73\x15\x14\xa5\x58\x29\xa4\x25\xe6\x14\xa7\x72\x71\x45\xa7\xa4\x96\xc1\xf4\x00\x99\x7a\x50\x7d\xc9\xf9\xb9\x10\xc5\x7a\x86\x26\x40\x45\x40\x1d\x68\x06\x83\x15\x80\x8d\x35\x31\x31\x86\x2b\x35\x34\x85\x18\x5e\x52\x54\x9a\xca\x05\x08\x00\x00\xff\xff\x4c\xd6\x29\x2b\x93\x00\x00\x00")

func sampleCfgBytes() ([]byte, error) {
	return bindataRead(
		_sampleCfg,
		"sample.cfg",
	)
}

func sampleCfg() (*asset, error) {
	bytes, err := sampleCfgBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "sample.cfg", size: 147, mode: os.FileMode(420), modTime: time.Unix(1451200624, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _databaseCfg = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x8a\x76\x71\x75\x73\x0c\xf5\x09\x89\xe5\x4a\x49\xca\xc8\x2f\x2e\xb1\x52\xc8\xc9\x4f\x4e\xcc\x01\x31\x81\x22\x05\xf9\x45\x40\x11\x63\x63\x03\x33\x2e\xae\xe8\x94\xd4\x32\x84\x2a\x20\x27\x25\x49\x0f\xac\x96\x0b\x49\x15\x20\x00\x00\xff\xff\x9f\xf9\x1e\xd9\x4f\x00\x00\x00")

func databaseCfgBytes() ([]byte, error) {
	return bindataRead(
		_databaseCfg,
		"database.cfg",
	)
}

func databaseCfg() (*asset, error) {
	bytes, err := databaseCfgBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "database.cfg", size: 79, mode: os.FileMode(420), modTime: time.Unix(1451224153, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"sample.cfg": sampleCfg,
	"database.cfg": databaseCfg,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"database.cfg": &bintree{databaseCfg, map[string]*bintree{}},
	"sample.cfg": &bintree{sampleCfg, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

